---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- include: setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Copy exports file.
  template:
    src: "{{ nfs_exports_template_path }}"
    dest: /etc/exports
    owner: root
    group: root
    mode: 0644
  notify: restart nfs

- name: Ensure NFS is started and enabled.
  service: name="{{ nfs_server_daemon }}" state=started enabled=yes
  when: nfs_exports|length
