---
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define nfs_service.
  set_fact:
    nfs_service: "{{ __nfs_service }}"
  when: nfs_service is not defined

- include: setup-RedHat.yml
  when: ansible_os_family == "RedHat"

- name: Copy /etc/exports.
  template: src=exports.j2 dest=/etc/exports owner=root group=root
  notify: restart nfs

- name: Start and enable NFS.
  service: name={{ nfs_service }} state=started enabled=yes
  when: nfs_exports|length
